Redis integration and code refactor
ushahidi/platform-api-ussd-service pull request #27
Opened 2019-08-12 09:38 UTC by Timtech4u

This PR contains the working code for Redis integration, allows saving valid responses to a Redis DB.

Work is in progress for adding validity check using Regex.

Issue #26

2019-08-12 10:46 UTC, tuxpiper commented on app.py
> +        ussdTextList = request_data['text'].split('*')
side note: did we ever test what would happen if the user entered text with asterisk symbols in it?

2019-08-12 11:20 UTC, tuxpiper reviewed
I'm finding it pretty hard to follow how the app is storing state in Redis. May I suggest creating a separate class/module that is solely responsible of formatting in and parsing out data from Redis?

It would really make the code cleaner, sp. if that class/module has methods/functions that are easy to understand, from the perspective of what info the main module is operating with (i.e. get_form_id , get_fields .. etc )

2019-08-12 11:20 UTC, tuxpiper commented on app.py
> +        while '' in ussdTextList:
wouldn't filter() ( https://docs.python.org/3/library/functions.html#filter ) be a better approach?

Modifying a list while iterating on it is a source of concern for me (and others as well, i.e.: https://unspecified.wordpress.com/2009/02/12/thou-shalt-not-modify-a-list-during-iteration/ )

2019-08-12 11:20 UTC, tuxpiper commented on app.py
> +        while '' in ussdTextList:
Also, why would there be empty elements in the list and how removing them would affect step count?

2019-08-12 11:20 UTC, tuxpiper commented on app.py
> +        if len(redis_db.get(session_id)) >= 1:
is this equivalent to `validStep >=1` ?  If so, using that expression would make the flow a bit easier to understand while reading the code (imho)

2019-08-12 11:20 UTC, tuxpiper commented on setup.py
> +import redis
is there any corresponding entry for this module in requirements.txt ? I don't see one neither here on in master.

2019-08-12 12:46 UTC, Timtech4u commented on app.py
> +        ussdTextList = request_data['text'].split('*')
This splits the value into two e.g. If I entered `Local*Elections`, the final output is *['Local', 'Elections']

A way to go around this is to have any user input with * not valid, we could ask the user to use a different symbol if necessary.

What do you suggest?

2019-08-12 12:48 UTC, Timtech4u commented
> I'm finding it pretty hard to follow how the app is storing state in Redis. May I suggest creating a separate class/module that is solely responsible of formatting in and parsing out data from Redis?
> 
> It would really make the code cleaner, sp. if that class/module has methods/functions that are easy to understand, from the perspective of what info the main module is operating with (i.e. get_form_id , get_fields .. etc )

Thanks for the feedback, I'll refactor the codes and adopt a module for redis methods.

2019-08-12 12:51 UTC, Timtech4u commented on app.py
> +        while '' in ussdTextList:
The initial **ussdTextList** from Africa's Talking has a `''` in it.
Since we're working with the first step which starts at 0, we need to remove the initial `''` so it's initial length i.e. *step* gives us 0, not 1.

2019-08-12 12:54 UTC, Timtech4u commented on setup.py
> +import redis
Oops, nice catch, I'll add the *redis* package right away.

2019-08-12 12:54 UTC, Timtech4u commented on app.py
> +        if len(redis_db.get(session_id)) >= 1:
Sure, that'll go into my next commit.

2019-08-12 13:16 UTC, Timtech4u commented on app.py
> +        while '' in ussdTextList:
To be clear, I made use of *while* (which checks if there's a `''` is in the list), not too sure if this adopts iteration, but I'd check :+1:

2019-08-12 14:26 UTC, Timtech4u commented
> > I'm finding it pretty hard to follow how the app is storing state in Redis. May I suggest creating a separate class/module that is solely responsible of formatting in and parsing out data from Redis?
> > It would really make the code cleaner, sp. if that class/module has methods/functions that are easy to understand, from the perspective of what info the main module is operating with (i.e. get_form_id , get_fields .. etc )
> 
> Thanks for the feedback, I'll refactor the codes and adopt a module for redis methods.

@tuxpiper  could you confirm if you're able to easily read through the Redis integration with my latest commit.

2019-08-13 12:21 UTC, tuxpiper commented on app.py
> +        while '' in ussdTextList:
oh yep you are right :+1: my bad, brain is still coming back from vacation

2019-08-13 12:49 UTC, tuxpiper requested changes
Thanks! The latest changes do help. I just have one issue about cleaning up redis entries when they are not needed anymore.

2019-08-13 12:49 UTC, tuxpiper commented on app.py
> +        ussdTextList = request_data['text'].split('*')
It would be so much better if Africa's Talking did something with those asterisks ... 

How would we even know that the user has entered an '*' ?  Anyway, this probably deserves its own issue.

2019-08-13 12:49 UTC, tuxpiper commented on app.py
> +
how about removing unnecessary entries from Redis so that they don't accummulate? Would that be done somewhere here?

2019-08-15 14:35 UTC, tuxpiper commented
@rowasc did you get a chance to review?

2019-08-15 14:37 UTC, rowasc reviewed
so sorry I forgot to submit it , @tuxpiper @Timtech4u only a couple questions

2019-08-15 14:37 UTC, rowasc commented on utils.py
> +def validate_input(value, type):
just adding the note about looking into https://pypi.org/project/validation/ as mentioned in the call

2019-08-15 14:37 UTC, rowasc commented on .gitignore
> +redis-play.py
oooo what's this? is it like a configuration file for Redis?

2019-08-17 06:38 UTC, Timtech4u commented on app.py
> +
Hi @tuxpiper , yes, I'd delete the key in my next commit.

2019-08-17 06:47 UTC, Timtech4u commented on .gitignore
> +redis-play.py
This is a test file I used when learning Redis. Thanks for the catch.

2019-08-17 12:44 UTC, tuxpiper approved these changes
Looking good to me! :+1:

2019-08-18 03:08 UTC, rowasc approved these changes
🎉

2019-08-18 03:24 UTC, Timtech4u commented
Thanks @rowasc  @tuxpiper

2019-08-18 03:24 UTC, merged