Added Docker file
ushahidi/platform-api-ussd-service pull request #4
Opened 2019-06-12 12:11 UTC by Timtech4u

Added Docker file for Deployment to AWS Fargate

2019-06-12 17:03 UTC, tuxpiper requested changes

2019-06-12 17:03 UTC, tuxpiper commented on Dockerfile
> +
I'd suggest using WORKDIR to set up the location in the container filesystem where the app will be "installed"

2019-06-12 17:03 UTC, tuxpiper commented on Dockerfile
> +      && pip install -r requirements.txt
1. I'd suggest to separate the installation of requirements into its own RUN statement , and...
2. Place a COPY statement for the requirements.txt file *only*, right before the new RUN statement I mentioned above
    * btw, is this really working now? I think the build process wouldn't be able to find the requirements.txt file, since it hasn't been copied into the container yet

2019-06-12 17:03 UTC, tuxpiper commented on Dockerfile
> +CMD python app.py
Bonus points if you could set up the container *not* to run as root user , but we can always get back to that later.

2019-06-18 10:28 UTC, Timtech4u commented
Hi @tuxpiper , I totally chaged the Dockerfile to another that works.
Kindly help review.

2019-06-19 16:38 UTC, tuxpiper approved these changes
Some optimisations suggested if time allows, but otherwise this should work :+1:

2019-06-19 16:38 UTC, tuxpiper commented on Dockerfile
> +RUN apt-get update -y
Lines 2 and 3 can go in a single RUN statement, as in :

```
RUN apt-get update && \
    apt-get install -y python-pip python-dev build-essential
```

The logic is that there is no useful output in just updating the list of packages, the list is updated because we would like to install pip and other deps. So it makes sense to put the results of these two actions in the same layer.

Even more, usually a third line is added as in :
```
RUN apt-get update && \
    apt-get install -y python-pip python-dev build-essential && \
    apt-get clean && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

This removes all the package indexes, downloaded package files and any other temporary files generated. That way the resulting image is smaller.

Note that this cleanup is done in the same RUN statement and not a different one. The reason is that each statement in the Dockerfile creates a independently stored layer. When the image is created, all the layers are just packed together. When the image is unpacked in the server for running it, the changes of each layer are just applied in order.

So, while further layers can mark files created by other layers as removed (i.e. you can `RUN rm -fr /` at the end of the Dockerfile and that will make the image *look* empty), that won't remove the files from the layer where they were created, or the resulting image file.

2019-06-19 16:38 UTC, tuxpiper commented on Dockerfile
> +RUN pip install -r requirements.txt
This may still not be optimal for build times, because the line 4 copies everything in the source folder. *Any* changes in the source code will invalidate the cache for line 4 and cause lines 5 and 6 to be built again. Requirements will be pulled and installed again.

Whereas this:
```
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app
```
means that unless requirements.txt is updated, requirements won't be installed again. Changes to the application source code only affect the last line.

To be honest, this is not a big difference in a small project, but in a bigger one (with lots of dependencies) it saves a lot of developer time.

2019-06-19 16:41 UTC, tuxpiper commented
Oh one more suggestion. Add a `.dockerignore` file for files that doesn't need to be in the docker image. This is often `.git` (unless necessary for any reason while running the app) and whatever stuff local tools (i.e. pipenv) create.

2019-06-21 06:26 UTC, merged